// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xlitpoqjdxbwtwrdxqls.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhsaXRwb3FqZHhid3R3cmR4cWxzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjQzOTMsImV4cCI6MjA2NTUwMDM5M30.Pe-FMtt2HNhRzDcfEaF7UC1dYJlkVHZlM_bmu5Atgbo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);